version: "3"

services:
   php:
      build: ./php
      depends_on:
         - sql
      env_file:
         - ./docker-compose.env
      volumes:
         - ./php/Classes:/var/www/Classes
         - ./php/public_html:/var/www/public_html
         - ./php/lib:/var/www/lib
   app:
      build: ./app
      depends_on:
         - php
      ports:
         - 80:80
   sql:
      build: ./sql
      volumes:
         - foody:/var/lib/mysql
      env_file:
         - ./docker-compose.env
volumes:
   foody: